[package]
name = "playground"
version = "0.1.0"
authors = ["Logan <hs.lee.logan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.6.2" }
specs = "0.15.1"
specs-derive = "0.4.0"
